### PR TITLE
feat(molecule/inputField): update input version

### PR DESCRIPTION
**Pull request by andresz1**
## Molecule/InputField
**TASK**: None

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description, Motivation and Context
This PR updates `AtomInput` version

### CODE REVIEW

**Review by andresin87 — APPROVED** [review]

**Review by arnau-rius — APPROVED** [review]

**Comment by arnau-rius** [comment]
Should it be a breaking change?

**Review by javiauso — APPROVED** [review]

**Comment by andresz1** [comment]
@arnau-rius I think so because there was a breaking change in the `AtomInput` component (see [PR](https://github.com/SUI-Components/sui-components/pull/1289))

**Comment by arnau-rius** [comment]
> @arnau-rius I think so because there was a breaking change in the `AtomInput` component (see [PR](https://github.com/SUI-Components/sui-components/pull/1289))

Well it is merged already, I was saying it because in the PR description the breaking change checkbox was not checked! No problem 👍🏽

**Comment by andresz1** [comment]
oops! yes you are right I updated the description for the record @arnau-rius thanks!

**Pull request merged**
