### PR TITLE
feat(form/textInput): add onKeyPress keyboard event

### PR DESCRIPTION
**Pull request by elhoucine**
Add onKeyPress event to give the user the possibility to listen on some keyboard events like taking

action when the user presses `Enter` key.

ISSUES CLOSED: #359

### CODE REVIEW

**Review by carlesnunez — APPROVED** [review]
LGTM :)

**Review by midudev — APPROVED** [review]
👏 Awesome!!!

**Review by davidbarna — APPROVED** [review]

**Review by JoanClaret — APPROVED** [review]
👍 great!

**Review by jcger — APPROVED** [review]

**Comment by carlesnunez** [comment]
I've fixed conflicts so after a quick check seems to be ready to merge.

**Pull request merged**
