### PR TITLE
fix(atom/button): fix negative state of link

### PR DESCRIPTION
**Pull request by andresz1**
## Atom/Button
**TASK**: None

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### Description, Motivation and Context
This PR fixes negative state of link

### CODE REVIEW

**Comment by turolopezsanabria** [comment]
🙏🏻 @andresin87 @andresz1 
can you attach please screenshots showing how this change looks like in other themes?
FC, IJ, CN,  etc

**Comment by andresz1** [comment]
> 🙏🏻 @andresin87 @andresz1
> can you attach please screenshots showing how this change looks like in other themes?
> FC, IJ, CN, etc

Looks like the deploy preview is not working as expected

**Comment by andresz1** [comment]
> 🙏🏻 @andresin87 @andresz1
> can you attach please screenshots showing how this change looks like in other themes?
> FC, IJ, CN, etc

Here is the preview https://sui-components-73fmmdfyz-schibstedspain.vercel.app/workbench/atom/button/demo

Last Article, enable negative prop RadioButton

**Comment by turolopezsanabria** [comment]
Attaching image for better understanding of the impact

link button negative

**Review by andresin87 — APPROVED** [review]

**Pull request merged**
