### PR TITLE
feat(components/molecule/avatar): Add muted variant

### PR DESCRIPTION
**Pull request by stivaliserna**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### Description, Motivation and Context

This PR adds a new avatar badge variation: `muted`.

This variation will be used for the new avatar theme in Milanuncios. 

### Screenshots - Animations

Screenshot 2021-08-23 at 11 23 52

### CODE REVIEW

**Review by andresz1 — APPROVED** [review]

**Review by adriadoz — APPROVED** [review]

**Review by nistadev — APPROVED** [review]

**Comment by andresin87** [comment]
can you please show it in a demo?

**Comment by stivaliserna** [comment]
> can you please show it in a demo?

Hey @andresin87! The new variation is added automatically to the demo, you can check it in the deploy preview. Is that what you meant?

**Comment by andresin87** [comment]
> > can you please show it in a demo?
> 
> Hey @andresin87! The new variation is added automatically to the demo, you can check it in the deploy preview. Is that what you meant?

in the demo sizes?

**Comment by stivaliserna** [comment]
> in the demo sizes?

Under "Badge status" section.

**Comment by turolopezsanabria** [comment]
thnx @stivaliserna !
please wait for me to check with @diego on the initial request before merging this one, thnx

quick observations: 
- IMO, the status should be more informative maybe "inactive", "logged-out" or else, instead of "muted"
- It should be one of the statuses (as in current line 26 for instance)
- the new color breaks the style consistency, as it's adding an extra circle inside

**Review by oriolpuig — APPROVED** [review]

**Review by andresin87 — APPROVED** [review]

**Comment by turolopezsanabria** [comment]
👏🏼  thank you!

**Pull request merged**
