### PR TITLE
feat(molecule/field): inline takes 100% of width available

### PR DESCRIPTION
**Pull request by juanmaguitar**

### CODE REVIEW

**Review by devictoribero — APPROVED** [review]
For me it's a bit strange that the `inline prop` makes the components act as a `block`.

**Review by devictoribero — COMMENTED** [review]
missclick on approve

**Review by devictoribero — CHANGES_REQUESTED** [review]
I thought that clicking comment would dismiss the approve 😆

**Comment by juanmaguitar** [comment]
@tureey That's right. But this `inline` is not a CSS `inline`, it's a name for the prop that will display the elements in a line. And these components are supposed to take the 100% of the container, so we can decide the width of the field, by setting the width of the container

What do you think? Maybe another name for the prop would be less confusing?

**Comment by devictoribero** [comment]
Yes it makes sense now @juanmaguitar!

I can't find a name for that.. :( if anyone has any idea... share it please! If not, let it as it's now

**Review by devictoribero — APPROVED** [review]

**Review by rmoralp — APPROVED** [review]

**Comment by jcger** [comment]
Isn't inline the default described by ux? In this case, the default value should be true

No demo example?

**Comment by juanmaguitar** [comment]
@jcger If I remember correctly, I was asked by UX specifically to remove these inline examples of the demo because they were no part of the specification
Anyway, as we're adding this use case for `fieldSelect` it would have sense to also add this use case to `fieldInput` and `fieldTextarea`

**Pull request merged**
