### PR TITLE
fix(atom/slider): resulting slider behavior

### PR DESCRIPTION
**Pull request by andresin87**
there was a bug in an invalid window slider due to a margin provided not in % to the component:

--> visible in the slider example with margin values from 6000 to 60000

[old](https://sui-components.now.sh/workbench/atom/slider/demo)
[new](https://sui-components-git-fix-slider-behaviour.schibstedspain.now.sh/workbench/atom/slider/demo)

### CODE REVIEW

**Review by jcger — APPROVED** [review]

**Review by ferransimon — APPROVED** [review]

**Review by nguasch — CHANGES_REQUESTED** [review]
in the previous PR there are some changes in styles that broke compatibility

**Comment by andresin87** [comment]
> in the previous PR there are some changes in styles that broke compatibility

reviewing

**Review by nguasch — CHANGES_REQUESTED** [review]
It's Ok, but we need to set a couple of vars on label:
`margin-left: $ml-atom-slider-label;` (it was deleted on the previous PR)
`transform: translateX(-50%);` to rewrite it in our theme

**Review by midudev — APPROVED** [review]

**Comment by andresin87** [comment]
> It's Ok, but we need to set a couple of vars on label:
> `margin-left: $ml-atom-slider-label;` (it was deleted on the previous PR)
> `transform: translateX(-50%);` to rewrite it in our theme

done

**Pull request merged**
