### PR TITLE
feat(atom/panel): add the ability to set box-shadow to panel through a prop

### PR DESCRIPTION
**Pull request by a-ferrante**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### Description, Motivation and Context
Add the posibility to set box shadow to panel using a new prop called boxShadow. 
It will use the box shadow values defined in the sui-theme (m and l)

### Screenshots - Animations
Captura de pantalla 2021-03-18 a las 10 25 10

### CODE REVIEW

**Comment by andresin87** [comment]
I think the M size is more darker than the L and the blur of this one is too much. @turolopezsanabria can u confirm the proposed box-shadows are the defined by DS team?

Anyway, please, if we are offering an scale of box-shadows is difficult to understand there is no S size despite of having M n L.

I know there is not a defined box-shadow for that sizes in @s-ui/theme/lib/settings/_box-style.scss
```scss
// Box shadows
$bxsh-m: 0 1px 4px 0 rgba(0, 0, 0, 0.24) !default;
$bxsh-l: 0 3px 8px 0 rgba(0, 0, 0, 0.16) !default;
```
...but maybe it might be...

some references:

- [material-ui paper elevation](https://material-ui.com/components/paper/)
- [chakra-ui shadow](https://chakra-ui.com/docs/features/style-props#shadow)
- [ant-design paper hoverable](https://ant.design/components/card/)
- [react-toolbox card raised](http://react-toolbox.io/#/components/card)
- [semantic-ui card raised](https://react.semantic-ui.com/views/card/)

I personally prefer `elevation` for the prop naming offering the prop effect over how it is implemented.

**Comment by a-ferrante** [comment]
@andresin87 who should define the box-shadow token values? i can add the s token to the sui-theme if the info is provided.

I like the elevation prop and elevated adjective for this, i will update the code.
`
<panel elevation={0}/>
<panel elevation={1}/>
<panel elevation={2}/>
<panel elevation={3}/>
`
for none, s m and l?

this having in mind that we dont have the s defined yet

**Comment by turolopezsanabria** [comment]
Thank you both fo the comments:
I agree with this approach too:
<panel elevation={0}/> <panel elevation={1}/> <panel elevation={2}/> <panel elevation={3}/>

Please use this value for the S size:
$bxsh-s: 0 1px 1px 0 rgba(0, 0, 0, 0.24) !default;

box shadow Small

**Comment by a-ferrante** [comment]
@turolopezsanabria @andresin87 
PR to add the new token https://github.com/SUI-Components/sui-theme/pull/229

**Review by andresin87 — APPROVED** [review]

**Review by manjarcode — APPROVED** [review]

**Pull request merged**
