### PR TITLE
feat(components/molecule/accordion): add @s-ui/react-atom-polymorphic…

### PR DESCRIPTION
**Pull request by jmanrumartinez**
## molecule/accordion

**TASK**: MMAA-28814

### Types of changes

- [ ] 🪲 Bug fix (non-breaking change which fixes an issue)
- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🧾 Documentation
- [ ] 📷 Demo
- [ ] 🧪 Test
- [ ] 🧠 Refactor
- [ ] 💄 Styles

### Description, Motivation and Context

Add forgotten @s-ui/react-atom-polymorphic-element dependency

### Screenshots - Animations

Captura de pantalla 2022-05-31 a las 17 16 52

### CODE REVIEW

**Review by andresz1 — APPROVED** [review]

**Comment by tonyghiani** [comment]
Actually we should use the primitive component: https://github.com/SUI-Components/sui-components/tree/master/components/primitive/polymorphicElement

The one defined in the atom folder is the first implementation we did, but it should be removed once there are no more usages of it and we move completely to the primitive one :)

**Comment by andresin87** [comment]
The problem is in L7 of the AccordionItemPanel.js file. Could you please update the import to the previously mentioned by @tonyghiani anf remove the atom import?

**Review by andresin87 — CHANGES_REQUESTED** [review]
.

**Comment by jmanrumartinez** [comment]
Done! Thanks @tonyghiani @andresin87 :D

**Review by andresin87 — APPROVED** [review]

**Pull request merged**
