### PR TITLE
Feature/molecule accordion default opened tab

### PR DESCRIPTION
**Pull request by ivanmlaborda**
Add defaultOpenedTabs prop to sui molecule Accordion component.

imatge

### CODE REVIEW

**Review by AgonisticKatai — APPROVED** [review]

**Review by adriadoz — APPROVED** [review]

**Comment by andresin87** [comment]
It might also cover the muilti-opened-tab (Array on indexes)

**Comment by ivanmlaborda** [comment]
> It might also cover the muilti-opened-tab (Array on indexes)

Maybe open more than one tab by default (but not all tabs) is a strange edge case. Isn't it?

And it will create problems with autoclose. If two tabs are opened by default and the user open another one, the two default tabs will be closed, and it will seem strange for the user.

**Comment by andresin87** [comment]
> > It might also cover the muilti-opened-tab (Array on indexes)
> 
> Maybe open more than one tab by default (but not all tabs) is a strange edge case. Isn't it?
> 
> And it will create problems with autoclose. If two tabs are opened by default and the user open another one, the two default tabs will be closed, and it will seem strange for the user.

It needs to attend Accordion with no autoclose cases

**Review by seremejvaz — APPROVED** [review]

**Comment by ivanmlaborda** [comment]
> > > It might also cover the muilti-opened-tab (Array on indexes)
> > 
> > 
> > Maybe open more than one tab by default (but not all tabs) is a strange edge case. Isn't it?
> > And it will create problems with autoclose. If two tabs are opened by default and the user open another one, the two default tabs will be closed, and it will seem strange for the user.
> 
> It needs to attend Accordion with no autoclose cases

Ok, I have refactored to support multiple default opened tabs. Now defaultOpenedTabs prop has to be an array of indexes (numbers).

**Review by andresin87 — APPROVED** [review]

**Pull request merged**
