### PR TITLE
feat(components/molecule/drawer): Drawer content vertical grow

### PR DESCRIPTION
**Pull request by manjarcode**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### Description, Motivation and Context
Allow Drawer content to grow vertically in order to fill the space

### Screenshots - Animations
Before:
drawer before

After:
drawer after

### CODE REVIEW

**Comment by andresin87** [comment]
- react-MoleculeDrawer-content: is fullHeight
- react-MoleculeDrawer-content-body: is inline height

What do you need?

**Comment by manjarcode** [comment]
@andresin87 I need the background to be grey, but I don't want to modify it for the whole vertical in the theme just for this case, so since I can't edit the background for the instance I need the content to fill the space in order to use the background of the child

**Comment by andresin87** [comment]
create a scss token to make the content background color editable and replace that content in your vertical.

**Comment by manjarcode** [comment]
@andresin87 there is a token already for the background color, but I don't want to define the default color just for this case, I'm trying to implement this:

image

**Comment by andresin87** [comment]
Wait. Let me see

the `<div className="react-MoleculeDrawer-content-body">{children}</div>` wrapper is unnecesary.

add `display: block;` to the content and render directly the {children} inside the content (remove the body wrapper)

**Comment by manjarcode** [comment]
@andresin87  I just applied the changes you requested!

**Review by andresin87 — APPROVED** [review]

**Pull request merged**
