### PR TITLE
feat(topbar/user): remove notifications in top bar component

### PR DESCRIPTION
**Pull request by siscu**
Remove notifications in topbar user component.

image

### CODE REVIEW

**Review by davidbarna — APPROVED** [review]
Are you moving this code to somewhere else ?

**Comment by naxhh** [comment]
Shouldnt we deprecate this one and use topbar/composable ?

**Comment by siscu** [comment]
@davidbarna Yes now the notifications will be in the dropdown component, i am working in that ;)

**Comment by siscu** [comment]
@naxhh Redirect --> question to @kikoruiz: What do you think about this?

**Comment by kikoruiz** [comment]
@naxhh No, they are different topbars. What we'll do, regarding the new architucture of SUI Components, is to rename every custom topbar and put them in a specific folder (`header`). Check https://docs.google.com/document/d/1hG6-9LtPtVNd_b3pZ7FSheSMTuRvGjMG91CA81h5URI/edit#heading=h.lsnzhng23xsy.

**Review by kikoruiz — APPROVED** [review]

**Review by JoanClaret — APPROVED** [review]

**Comment by JoanClaret** [comment]
image
 🎉 🎉 🎉 🎉

**Review by naxhh — APPROVED** [review]

**Pull request closed without merging**
