### PR TITLE
fix/image-placeholder

### PR DESCRIPTION
**Pull request by jcger**
As svg resize is broken in IE11 this component does not allow <svg> node as placeholder/fallback anymore. For now on, use placeholder/fallback.src in order to set your svg's (see playground file)

### CODE REVIEW

**Review by PablitoGS — APPROVED** [review]

**Comment by davidbarna** [comment]
What do you been by svg resize broken ??

**Comment by jcger** [comment]
I mean that svg with width/height do not resize/scale

**Comment by davidbarna** [comment]
But SVGs meant to be used as icons should not have width and height. Only viewbox. It's a convention for SVG scaling.
The problem is that I've have a different approach with buttons and we must have the same approach. Can you send me a SVG example so I've checkout it there is a better solution? You can merge this if you need it. Don't want to be a stopper.

**Review by davidbarna — APPROVED** [review]

**Comment by jcger** [comment]
SVG wasn't used as icon in this PR, it was used as a placeholder and the placeholder has to resize in order to fill the same space as the image that is being loaded but as IE11 does not resize the svg, it was broken.

**Pull request merged**
