### PR TITLE
Feature/fix dropdownlist and select

### PR DESCRIPTION
**Pull request by davidmartin84**

### CODE REVIEW

**Review by jordevo — APPROVED** [review]

**Review by AgonisticKatai — APPROVED** [review]

**Comment by andresin87** [comment]
broken demo: [https://sui-components-git-feature-fix-dropdownlist-and-select.schibstedspain.now.sh/workbench/molecule/select/demo](https://sui-components-git-feature-fix-dropdownlist-and-select.schibstedspain.now.sh/workbench/molecule/select/demo)

**Comment by davidmartin84** [comment]
> broken demo: https://sui-components-git-feature-fix-dropdownlist-and-select.schibstedspain.now.sh/workbench/molecule/select/demo

puede ser por esto? 

`@extend %sui-atom-input-select-focus;`

que viene en mi otra PR: https://github.com/SUI-Components/sui-theme/pull/213 ?

**Review by rmoralp — APPROVED** [review]

**Comment by rmoralp** [comment]
Si, integra y publica el theme para probarlo bien.

**Comment by andresin87** [comment]
> > broken demo: [sui-components-git-feature-fix-dropdownlist-and-select.schibstedspain.now.sh/workbench/molecule/select/demo](https://sui-components-git-feature-fix-dropdownlist-and-select.schibstedspain.now.sh/workbench/molecule/select/demo)
> 
> puede ser por esto?
> 
> `@extend %sui-atom-input-select-focus;`
> 
> que viene en mi otra PR: [SUI-Components/sui-theme#213](https://github.com/SUI-Components/sui-theme/pull/213) ?

I suppose until its not integrated it could not be reproduced, and breakes the styling behavior

**Comment by davidmartin84** [comment]
> > > broken demo: [sui-components-git-feature-fix-dropdownlist-and-select.schibstedspain.now.sh/workbench/molecule/select/demo](https://sui-components-git-feature-fix-dropdownlist-and-select.schibstedspain.now.sh/workbench/molecule/select/demo)
> > 
> > 
> > puede ser por esto?
> > `@extend %sui-atom-input-select-focus;`
> > que viene en mi otra PR: [SUI-Components/sui-theme#213](https://github.com/SUI-Components/sui-theme/pull/213) ?
> 
> I suppose until its not integrated it could not be reproduced, and breakes the styling behavior

ya funciona la demo! he mergeado el theme.

**Review by andresin87 — COMMENTED** [review]
This change is modifying the default width-height behavior of the dropdown, setting it out of its wrapper bounds. I'm still investigating why

**Review by andresin87 — CHANGES_REQUESTED** [review]
According to @davidmartin84, he would change the `box-sizing` setting from `initial` to `inherit` to prevent the previous described changes

**Review by andresin87 — APPROVED** [review]

**Pull request merged**
