### PR TITLE
fix(atom/checkbox): prevent execute onChangeFromProps as undefined

### PR DESCRIPTION
**Pull request by rmoralp**
Fix error when onChange is undefined.
image

EDIT: MoleculeSelect is not passing this prop

### CODE REVIEW

**Review by jordevo — APPROVED** [review]

**Comment by midudev** [comment]
Then the `prop` is not required anymore. You should remove the `isRequired` property.

**Review by devictoribero — APPROVED** [review]

**Comment by devictoribero** [comment]
@midudev This is something I always wanted to talk about. The fact this `prop` has a `defaultValue` doesn't mean it's not `required`, isn't it?

What I mean by this, is that it's still `required`, but it has a `defaultValue`. What does `require` mean for us? to pass it always every time we want to instance the component?

**Comment by midudev** [comment]
@tureey `isRequired` means that the component should not work if the prop is not provided, as giving a value is mandatory. If a default value is provided, then it means the prop is not required anymore as you could ommit it and the component will work without problems.

**Comment by devictoribero** [comment]
Ok! I always understood more in an API way. If the prop is required, but it has a default value, it's not provided by the user, but somehow its provided so it should work!

But I think that how you pointed out is how everyone understands it xD thanks @midudev !

**Comment by rmoralp** [comment]
I have removed isRequired from proptypes.

**Review by carlosvillu — APPROVED** [review]

**Review by AgonisticKatai — APPROVED** [review]

**Review by midudev — APPROVED** [review]

**Pull request merged**
